/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
(Param loss escolhido: mean_squared_error
(Param optimizer escolhido: adadelta
(Param activation escolhido: crelu
Traceback (most recent call last):
  File "testes_luis.py", line 89, in <module>
    model = tf.keras.models.load_model(filename)#= keras_model()        
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/models.py", line 246, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/models.py", line 324, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/layers/serialization.py", line 63, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/utils/generic_utils.py", line 164, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/models.py", line 1333, in from_config
    layer = layer_module.deserialize(conf, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/layers/serialization.py", line 63, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/utils/generic_utils.py", line 166, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 483, in from_config
    return cls(**config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/layers/core.py", line 778, in __init__
    activation=activations.get(activation),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/activations.py", line 119, in get
    return deserialize(identifier)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/activations.py", line 111, in deserialize
    printable_module_name='activation function')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/utils/generic_utils.py", line 184, in deserialize_keras_object
    function_name)
ValueError: Unknown activation function:crelu
